default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: newcarsales_development

test:
  <<: *default
  database: newcarsales_test


production:
  <<: *default
  database: newcarsales_production
  username: newcarsales
  password: <%= ENV["NEWCARSALES_DATABASE_PASSWORD"] %>
